#!/bin/bash --login

#SBATCH --nodes=1
#SBATCH --time=01:00:00
#SBATCH --account=m18


module swap PrgEnv-cray PrgEnv-gnu
module load cray-hdf5-parallel/1.8.13 python/2.7.10 swig numpy scipy cython mpi4py cmake pkgconfig

# python things
export PYTHONPATH=$PYTHONPATH:/ivec/cle52/magnus/python/2.7.6/six/1.9.0/lib/python2.7/site-packages/

module load mpi4py

export PYTHONPATH=$PYTHONPATH:/group/m18/dsandiford/underworld2

cd ..

aprun -n 16 python slab3d.py T 1
